# Generated by Django 3.0 on 2021-05-31 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ห้องศึกษาค้นคว้าอิสระ/ห้องเก็บวัสดุวิทยาศาสตร์และสารเคมี', 'ห้องศึกษาค้นคว้าอิสระ/ห้องเก็บวัสดุวิทยาศาสตร์และสารเคมี'), ('ห้องปฏิบัติการวิจัยเซลล์และชีวโมเลกุล', 'ห้องปฏิบัติการวิจัยเซลล์และชีวโมเลกุล'), ('ห้องปฏิบัติการเพาะเลี้ยงเซลล์', 'ห้องปฏิบัติการเพาะเลี้ยงเซลล์'), ('ห้องปฏิบัติการชีวโมเลกุล', 'ห้องปฏิบัติการชีวโมเลกุล'), ('ห้องปฏิบัติชีวเคมีและเคมีวิเคราะห์', 'ห้องปฏิบัติชีวเคมีและเคมีวิเคราะห์'), ('ห้องปฏิบัติการจุลชีววิทยาและปรสิตวิทยา', 'ห้องปฏิบัติการจุลชีววิทยาและปรสิตวิทยา'), ('ห้องปฏิบัติการเชื้อรา', 'ห้องปฏิบัติการเชื้อรา'), ('ห้องปฏิบัติการแบคทีเรีย', 'ห้องปฏิบัติการแบคทีเรีย'), ('ห้องปฏิบัติการพยาธิวิทยากายวิภาค', 'ห้องปฏิบัติการพยาธิวิทยากายวิภาค'), ('ห้องปฏิบัติการทางคลินิก', 'ห้องปฏิบัติการทางคลินิก'), ('ห้องปฏิบัติการโรคติดเชื้อ 1', 'ห้องปฏิบัติการโรคติดเชื้อ 1'), ('ห้องปฏิบัติการโรคติดเชื้อ 2', 'ห้องปฏิบัติการโรคติดเชื้อ 2')], max_length=100)),
                ('number', models.CharField(max_length=10, null=True)),
                ('intendant', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, default='lab.jpg', null=True, upload_to='lab_image')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=8)),
                ('objective', models.CharField(max_length=250, null=True)),
                ('applicant_status', models.CharField(choices=[('นักวิจัย', 'นักวิจัย'), ('อาจารย์', 'อาจารย์'), ('นิสิต', 'นิสิต'), ('', 'อื่นๆ')], default='นักวิจัย', max_length=20, null=True)),
                ('experiment_variable', models.CharField(blank=True, help_text='โปรดระบุชนิดหรือปริมาณสารเคมี,เซลล์หรือสิ่งที่เข้ามาใช้ในห้องทดลอง', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_category', models.CharField(choices=[('researcher', 'นักวิจัย'), ('student', 'นิสิต'), ('professor', 'อาจารย์'), ('other', 'อื่นๆ')], default='นักวิจัย', max_length=100)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('tel', models.CharField(max_length=10, null=True)),
                ('faculty', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=10, null=True)),
                ('photo_profile', models.ImageField(blank=True, default='default.png', null=True, upload_to='photo_profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_number', models.CharField(max_length=100, null=True)),
                ('equipment_name', models.CharField(max_length=200)),
                ('lender', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='device_image')),
                ('equipment_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edl_management.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_working', models.BooleanField(blank=True, null=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edl_management.Profile')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edl_management.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='BookEquipmentLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_reservation', models.DateTimeField()),
                ('end_reservation', models.DateTimeField()),
                ('comment', models.CharField(blank=True, help_text='The reason for this change', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('', 'No action taken')], default='', max_length=8)),
                ('category', models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=8)),
                ('objective', models.CharField(max_length=250, null=True)),
                ('experiment_variable', models.CharField(blank=True, help_text='โปรดระบุชนิดหรือปริมาณสารเคมี,เซลล์หรือสิ่งที่เข้ามาใช้ในห้องทดลอง', max_length=250)),
                ('applicant', models.ForeignKey(help_text='The user who authored the change', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edl_management.Equipment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edl_management.Project')),
            ],
        ),
    ]
