# Generated by Django 3.0 on 2021-06-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0002_auto_20210601_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equipment_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='equipment_number',
            new_name='number',
        ),
    ]
