# Generated by Django 3.0 on 2021-06-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0003_auto_20210603_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='picture',
            new_name='photo',
        ),
    ]
