# Generated by Django 3.0 on 2021-06-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0005_auto_20210603_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookequipmentletter',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bookequipmentletter',
            name='experiment_variable',
        ),
        migrations.RemoveField(
            model_name='bookequipmentletter',
            name='objective',
        ),
        migrations.AddField(
            model_name='profile',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
