# Generated by Django 3.0 on 2021-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0006_auto_20210611_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_category',
            field=models.CharField(choices=[('นักวิจัย', 'นักวิจัย'), ('นิสิต', 'นิสิต'), ('อาจารย์', 'อาจารย์'), ('อื่นๆ', 'อื่นๆ')], default='นักวิจัย', max_length=100),
        ),
    ]
