# Generated by Django 3.0 on 2021-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0007_auto_20210611_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookequipmentletter',
            name='confirm',
            field=models.BooleanField(help_text='โดยข้าพเจ้าได้อ่านระเบียบการใช้ห้องปฏิบัติการวิจัยกลางคณะวิทยาศาสตร์การแพทย์ มหาวิทยาลัยพะเยา และยินยอมปฏิบัติตามกฎระเบียบดังกล่าวทุกประการ ในระหว่างปฏิบัติงาน หากห้องปฏิบัติการ เครื่องมือ อุปกรณ์ เกิดการชำรุดหรือเสียหาย ข้าพเจ้ายินดีรับผิดชอบชดใช้ค่าเสียหายที่เกิดขึ้น', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='objective',
            field=models.CharField(choices=[('ทำวิจัย', 'ทำวิจัย'), ('การเรียนการสอน/IS', 'การเรียนการสอน/IS'), ('อื่นๆ', 'อื่นๆ')], default='ทำวิจัย', max_length=100),
        ),
    ]
