# Generated by Django 3.0 on 2021-06-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0008_auto_20210611_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_category',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='confirm',
            field=models.BooleanField(default=False, help_text='โดยข้าพเจ้าได้อ่านระเบียบการใช้ห้องปฏิบัติการวิจัยกลางคณะวิทยาศาสตร์การแพทย์ มหาวิทยาลัยพะเยา และยินยอมปฏิบัติตามกฎระเบียบดังกล่าวทุกประการ ในระหว่างปฏิบัติงาน หากห้องปฏิบัติการ เครื่องมือ อุปกรณ์ เกิดการชำรุดหรือเสียหาย ข้าพเจ้ายินดีรับผิดชอบชดใช้ค่าเสียหายที่เกิดขึ้น', null=True),
        ),
    ]
