# Generated by Django 3.0 on 2021-06-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0010_auto_20210613_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='confirm',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Deny', 'Deny')], default=False, help_text='โดยข้าพเจ้าได้อ่านระเบียบการใช้ห้องปฏิบัติการวิจัยกลางคณะวิทยาศาสตร์การแพทย์ มหาวิทยาลัยพะเยา และยินยอมปฏิบัติตามกฎระเบียบดังกล่าวทุกประการ ในระหว่างปฏิบัติงาน หากห้องปฏิบัติการ เครื่องมือ อุปกรณ์ เกิดการชำรุดหรือเสียหาย ข้าพเจ้ายินดีรับผิดชอบชดใช้ค่าเสียหายที่เกิดขึ้น', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='example',
            field=models.CharField(blank=True, help_text='สารตัวอย่างที่นำมาใช้งาน เช่น Freeze dry เช่น สารสกัดสมุนไพร, ชิ้นผลไม้, ข้าว (หากเป็นชิ้นงาน ควรจะมีขนาดหนาไม่เกิน 2 cm.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='substance',
            field=models.IntegerField(blank=True, help_text='ปริมาณสารทั้งหมดที่นำมาใช้ เช่น Freeze dry (เนื่องจากต้องมีปริมาณน้ำที่จำกัดในการFreeze dry อยู่ที่ไม่เกิน 2000 ml. ต่อการทำแห้ง 1 รอบ) ', null=True),
        ),
    ]
