# Generated by Django 3.0 on 2021-06-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0011_auto_20210613_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookequipmentletter',
            name='applicant',
        ),
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='confirm',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Deny', 'Deny')], help_text='โดยข้าพเจ้าได้อ่านระเบียบการใช้ห้องปฏิบัติการวิจัยกลางคณะวิทยาศาสตร์การแพทย์ มหาวิทยาลัยพะเยา และยินยอมปฏิบัติตามกฎระเบียบดังกล่าวทุกประการ ในระหว่างปฏิบัติงาน หากห้องปฏิบัติการ เครื่องมือ อุปกรณ์ เกิดการชำรุดหรือเสียหาย ข้าพเจ้ายินดีรับผิดชอบชดใช้ค่าเสียหายที่เกิดขึ้น', max_length=10, null=True),
        ),
    ]
