# Generated by Django 3.0 on 2021-06-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0012_auto_20210613_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookequipmentletter',
            name='status',
        ),
    ]
