# Generated by Django 3.0 on 2021-06-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0013_remove_bookequipmentletter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookequipmentletter',
            name='project',
        ),
        migrations.AddField(
            model_name='bookequipmentletter',
            name='project',
            field=models.ManyToManyField(to='edl_management.Project'),
        ),
    ]
