# Generated by Django 3.0 on 2021-06-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0014_auto_20210614_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='comment',
            field=models.CharField(blank=True, help_text='เหตุผลในการใช้งานครุภัณฑ์เพื่อประกอบคำร้อง', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='equipment',
            field=models.ForeignKey(help_text='ครุภัณฑ์ที่ต้องการใชงาน', on_delete=django.db.models.deletion.CASCADE, to='edl_management.Equipment'),
        ),
        migrations.RemoveField(
            model_name='bookequipmentletter',
            name='project',
        ),
        migrations.AddField(
            model_name='bookequipmentletter',
            name='project',
            field=models.ForeignKey(help_text='โครงการของผู้ยื่นคำร้องเพื่อประกอบคำร้อง', null=True, on_delete=django.db.models.deletion.CASCADE, to='edl_management.Project'),
        ),
    ]
