# Generated by Django 3.0 on 2021-06-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0015_auto_20210615_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookequipmentletter',
            name='status',
            field=models.CharField(choices=[('Select', 'Select'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Select', max_length=20),
        ),
    ]
