# Generated by Django 3.0 on 2021-06-18 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0016_bookequipmentletter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='catalyst',
            field=models.CharField(blank=True, help_text='สารตัวอย่างที่นำเร่่งปฎิกิริยา', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='equipment',
            field=models.ForeignKey(help_text='ครุภัณฑ์ที่ต้องการใช้งาน', on_delete=django.db.models.deletion.CASCADE, to='edl_management.Equipment'),
        ),
    ]
