# Generated by Django 3.0 on 2021-06-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0017_auto_20210618_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='unhide',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='end_reservation',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='start_reservation',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('นักวิจัย', 'นักวิจัย'), ('นิสิต', 'นิสิต'), ('อาจารย์', 'อาจารย์'), ('บุคคลภายนอก', 'บุคคลภายนอก')], default='นักวิจัย', max_length=100),
        ),
    ]
