# Generated by Django 3.0 on 2021-06-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0018_auto_20210620_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='end_reservation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='start_reservation',
            field=models.DateTimeField(),
        ),
    ]
