# Generated by Django 3.0 on 2021-06-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0019_auto_20210620_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='unhide',
        ),
    ]
