# Generated by Django 3.0 on 2021-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0020_remove_project_unhide'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='un_hide',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='end_reservation',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='start_reservation',
            field=models.DateTimeField(unique=True),
        ),
    ]
