# Generated by Django 3.0 on 2021-06-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0022_remove_project_un_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scientific_usage',
            field=models.CharField(blank=True, choices=[('endopoint', 'endopoint'), ('kinatic', 'kinatic')], help_text='ลักษณะการใช้งานภายในโครงการ', max_length=100, null=True),
        ),
    ]
