# Generated by Django 3.0 on 2021-06-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0023_project_scientific_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookequipmentletter',
            name='official_working',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
