# Generated by Django 3.0 on 2021-06-22 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0024_bookequipmentletter_official_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookequipmentletter',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='edl_management.Project'),
        ),
    ]
