# Generated by Django 3.0 on 2021-06-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edl_management', '0028_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
